# Generated by Django 5.0.6 on 2026-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crmuser_crmsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='period',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
