# Generated by Django 5.0.6 on 2026-07-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_payment_user_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to='api.crmuser'),
        ),
    ]
